### PR TITLE
[MS-3244] Add encryption support to Property entity

### PR DESCRIPTION
**Pull request by phil1618**

### CODE REVIEW

**Comment by phil1618** [comment]
@bsafta-meyvn Can you confirm that this PR is ready ? 

@aduchate No need to deploy that PR too quickly. We should sync it with the next Medispring Electron release.

**Comment by bsafta-meyvn** [comment]
> @bsafta-meyvn Can you confirm that this PR is ready ?
@phil1618  I can confirm that all my commits are ready to be merged as long as Antoine agrees with my changes.

**Comment by phil1618** [comment]
@bsafta-meyvn Cool. I think we could ask for this PR to be merged for the next (WEB+ELECTRON) release. If @aduchate agrees of course.

**Comment by aduchate** [comment]
Why this big unrelated change in SMF + the drugs.zip change ?

**Comment by gpiroux** [comment]
> Why this big unrelated change in SMF + the drugs.zip change ?

For the drugs.zip, cause it has been integrated in medispring master

**Comment by aduchate** [comment]
> > Why this big unrelated change in SMF + the drugs.zip change ?
> 
> For the drugs.zip, cause it has been integrated in medispring master

It might be a good idea to make PRs from feature branches

**Pull request merged**
